### ISSUE TITLE
Problems opening .drawio files with plugin in IntelliJ IDEA 2026.2 (NoClassDefFoundError)

### ISSUE THREAD

**Issue by JohnAlexJensen** [docToolchain/diagrams.net-intellij-plugin#406]
After updating to 2026.2 Diagrams.net 0.2.6 gives the following problem when trying to open drawio file:

failed rebuild request processing

java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JCEFHtmlPanel
	at de.docs_as_co.intellij.plugin.drawio.utils.LoadableJCEFHtmlPanel.<init>(LoadableJCEFHtmlPanel.kt:26)
	at de.docs_as_co.intellij.plugin.drawio.editor.BaseDiagramsWebView.<init>(BaseDiagramsWebView.kt:82)
	at de.docs_as_co.intellij.plugin.drawio.editor.DiagramsWebView.<init>(DiagramsWebView.kt:10)
	at de.docs_as_co.intellij.plugin.drawio.editor.DiagramsEditor.<init>(DiagramsEditor.kt:46)
	at de.docs_as_co.intellij.plugin.drawio.editor.DiagramsEditorProvider.createEditor(DiagramsEditorProvider.kt:52)
	at com.intellij.ide.impl.StructureViewWrapperImpl$createStructureViewBuilder$editor$1.invokeSuspend(StructureViewWrapperImpl.kt:656)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:42)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:246)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:228)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1$1$0(NonBlockingFlushQueue.kt:329)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:941)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1$1(NonBlockingFlushQueue.kt:328)
	at com.intellij.concurrency.ThreadContext.resetThreadContext(threadContext.kt:295)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1(NonBlockingFlushQueue.kt:325)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunWriteIntentReadAction(NestedLocksThreadingSupport.kt:753)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent(NonBlockingFlushQueue.kt:321)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.flushNow(NonBlockingFlushQueue.kt:299)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.FLUSH_NOW$lambda$0(NonBlockingFlushQueue.kt:158)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:323)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:732)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:711)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:731)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:384)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$0(IdeEventQueue.kt:1122)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1122)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:382)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:422)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.jcef.JCEFHtmlPanel PluginClassLoader(plugin=PluginMainDescriptor(name=Diagrams.net Integration, id=de.docs_as_co.intellij.plugin.diagramsnet, version=0.2.6, isBundled=false, path=~\AppData\Roaming\JetBrains\IntelliJIdea2026.2\plugins\diagrams.net-intellij-plugin), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.libraries.groovy, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Groovy Scripting, id=com.intellij.groovy.scripting, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\groovy-scripting), ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.xml.emmet) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.ssh.core, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh.attach) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.smRunner, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Test Runner, id=intellij.testRunner.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-testRunner-plugin), ContentModuleDescriptor(id=intellij.platform.structureView) <- PluginMainDescriptor(name=Structure View, id=intellij.structureView.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-structureView-plugin), ContentModuleDescriptor(id=intellij.platform.todo) <- PluginMainDescriptor(name=TODO Comments, id=intellij.todo.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-todo-plugin), ContentModuleDescriptor(id=intellij.platform.bookmarks, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Bookmarks Manager, id=intellij.bookmarks.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-bookmarks-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.structuralSearch) <- PluginMainDescriptor(name=Structural Search, id=intellij.structuralSearch.plugin, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\plugins\platform-structuralSearch-plugin), ContentModuleDescriptor(id=intellij.relaxng) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.spellchecker) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.spellchecker.xml) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.protocolReaderRuntime) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.backend) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.ui) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.tasks) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.tasks.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth.base) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.4\lib), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 38 more

IDE version:
IntelliJ IDEA 2026.2
Build #IU-262.8665.258, built on July 15, 2026
Source revision: 9db502cc722e2

**Comment by director74** [comment]
Temporary fix from AI while waiting fix in repo

Close the IDE and run in PowerShell:

```powershell
$dir = "$env:APPDATA\JetBrains\GoLand2026.2\plugins\diagrams.net-intellij-plugin\lib"
$jar = Get-ChildItem $dir -Filter *.jar | Where-Object {
    $z = [System.IO.Compression.ZipFile]::OpenRead($_.FullName)
    $has = $null -ne $z.GetEntry('META-INF/plugin.xml'); $z.Dispose(); $has
} | Select-Object -First 1

Copy-Item $jar.FullName "$($jar.FullName).bak"

$zip = [System.IO.Compression.ZipFile]::Open($jar.FullName, 'Update')
$e = $zip.GetEntry('META-INF/plugin.xml')
$sr = New-Object System.IO.StreamReader($e.Open())
$xml = $sr.ReadToEnd(); $sr.Close()

$xml = $xml -replace '(<depends>com\.intellij\.modules\.platform</depends>)',
                     "`$1`n    <depends>com.intellij.modules.jcef</depends>"

$s = $e.Open(); $s.SetLength(0)
$sw = New-Object System.IO.StreamWriter($s)
$sw.Write($xml); $sw.Flush(); $sw.Close(); $s.Close()
$zip.Dispose()
Write-Host "Patched: $($jar.FullName)"
```

If the descriptor is not picked up, delete %LOCALAPPDATA%\JetBrains\GoLand2026.2\caches (plugin descriptor cache).

**Comment by nsenoge63** [comment]
> Temporary fix from AI while waiting fix in repo
> 
> Close the IDE and run in PowerShell:
> 
> $dir = "$env:APPDATA\JetBrains\GoLand2026.2\plugins\diagrams.net-intellij-plugin\lib"
> $jar = Get-ChildItem $dir -Filter *.jar | Where-Object {
>     $z = [System.IO.Compression.ZipFile]::OpenRead($_.FullName)
>     $has = $null -ne $z.GetEntry('META-INF/plugin.xml'); $z.Dispose(); $has
> } | Select-Object -First 1
> 
> Copy-Item $jar.FullName "$($jar.FullName).bak"
> 
> $zip = [System.IO.Compression.ZipFile]::Open($jar.FullName, 'Update')
> $e = $zip.GetEntry('META-INF/plugin.xml')
> $sr = New-Object System.IO.StreamReader($e.Open())
> $xml = $sr.ReadToEnd(); $sr.Close()
> 
> $xml = $xml -replace '(<depends>com\.intellij\.modules\.platform</depends>)',
>                      "`$1`n    <depends>com.intellij.modules.jcef</depends>"
> 
> $s = $e.Open(); $s.SetLength(0)
> $sw = New-Object System.IO.StreamWriter($s)
> $sw.Write($xml); $sw.Flush(); $sw.Close(); $s.Close()
> $zip.Dispose()
> Write-Host "Patched: $($jar.FullName)"
> If the descriptor is not picked up, delete %LOCALAPPDATA%\JetBrains\GoLand2026.2\caches (plugin descriptor cache).

I tried this fix, it works perfectly.
Thanks

**Comment by Hollerweger** [comment]
When is the release planned for it?
I addition I don’t have the option anymore to open a .svg file via diagrams.net. I need to reassign svg extension to diagrams.net plugin.
Will this also work again when this issue is fixed?

**Comment by nsenoge63** [comment]
> When is the release planned for it? I addition I don’t have the option anymore to open a .svg file via diagrams.net. I need to reassign svg extension to diagrams.net plugin. Will this also work again when this issue is fixed?

@Hollerweger, did you try the fix suggested by @director74 ?

**Comment by Hollerweger** [comment]
No not yet, as I reverted to 2026.1 and this issue was closed, so i wanted to wait on the release. But I can do this test if you would like some feedback before releasing it

**Comment by ahus1** [comment]
The changes now in main should fix it. I plan for a release later this week or early next week.

**Comment by ahus1** [comment]
The pre-release v0.2.7 of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

It will also be from the EAP version stream once the JetBrains team approves the new version. 

Once I hear from you that it works as expected, I'll publish it to the stable release stream in the marketplace.

**Comment by ahus1** [comment]
As the plugin was using an internal API and this lead to an error in publishing, I prepared v0.2.8 does not use an internal API. 

As above, it is available from the GitHub releases. 

You can also use the EAP plugin repository as described in https://github.com/docToolchain/diagrams.net-intellij-plugin#installation

**Comment by ahus1** [comment]
I didn't hear back from anyone, but then still decided to move forward in publishing the plugin. 

v0.2.8 is now available from the marketplace.

**Comment by nsenoge63** [comment]
I just downloaded the new version.
It seems to work perfectly.

Thanks for the fix
